### ISSUE TITLE
motor controller component failure

### ISSUE THREAD

**Issue by edaniszewski** [BenningtonCS/Telescope-2014#107]
When attempting to test our fix to #106 , things got bad..

Below is a narrative describing what we did, for posterity, but the short version of it is that the controller is not working and appears to have a blown component on the bottom. We need to figure out what to do about it, or else we can't use the controller, i.e. can't use the telescope.

---

We managed to zero the controller with the dish pointing north. Then we were going to try and use the software to get it to point at the sun to see if we got it working correctly.

There was a burning/melty smell and the software was saying that it could not find anything in ttyUSB0, so it wasnt recognizing the controller. I checked to see if it was plugged in, it was, but the USB cable was very hot. 

The power supply fan was going, which indicated that it was pushing energy somewhere, but when the USB was unplugged, the fan slowed, so maybe it was pushing energy thorough the USB which would explain why it was heating up. 

We played around a little to try and figure out why this was happening (double checking connections, etc), then I checked the fuse, and it looked fine. After putting the fuse back in, the controller doesnt look like it was turning on -- no display readout was showing up. 

We checked all the wires again, made sure the fuse was in, etc, but couldnt find the problem -- Hugh came up and checked everything again, then we opened up the controller, the top looked OK, so we took out the board, and it looks like there is a component on the bottom that was blown.

**Comment by hcrowl** [comment]
Just cleaning up. This has been fixed for a while. @acencini and I traced it to some mis-wiring in the rotator and replaced the controller with a new one. The old one is there if someone wants to practice soldering.
