### ISSUE TITLE
Determine True North on the Roof of Dickinson

### ISSUE THREAD

**Issue by hcrowl** [BenningtonCS/Telescope-2014#122]
Let's determine True North once and for all.

Tomorrow, July 17, 2015, local noon* occurs at 13:07:04 (i.e. 1:07:04 PM) EDT. 

@theDarkLard and @hcrowl will meet on the roof of Dickinson at ~12:30 pm and set up a plumb bob. At the time of local noon, the shadow cast by the plumb bob will be exactly North-South. We will then use this line to determine True North. 

*(http://www.esrl.noaa.gov/gmd/grad/solcalc/sunrise.html used to look up local noon)

**Comment by theDarkLard** [comment]
Stoked.

**Comment by hcrowl** [comment]
Done.
