### ISSUE TITLE
Make a wiki entry on calibration instructions

### ISSUE THREAD

**Issue by theDarkLard** [BenningtonCS/Telescope-2014#32]
List and explain instructions for calibrating the t-scope:
-Calibrating the t-scope to work with the dongle mod
-Calibrating the t-scope for observing

**Comment by edaniszewski** [comment]
@theDarkLard 

can this issue be closed?
https://github.com/BenningtonCS/Telescope-2014/wiki/Calibrating-the-Telescope

**Comment by theDarkLard** [comment]
yar matey.
