### ISSUE TITLE
Client Crashes On Screensaver Start

### ISSUE THREAD

**Issue by Kgespada** [BenningtonCS/Telescope-2014#44]
They mention in the readme that screensavers will interfere with the software and that the user should disable any screensavers. Chances are we can do better than that, but this is far from a critical issue.

**Comment by edaniszewski** [comment]
is this still a problem? I think i remember in a different issue thread someone made mention that it doesn't behave this way anymore?

**Comment by theDarkLard** [comment]
Yeah I haven't had any problems with this.

**Comment by edaniszewski** [comment]
Whelp, I guess that means this can be closed (I'll give you the honors @theDarkLard ). It can always be re-opened if it becomes an issue.
